  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '22'

  - name: Install CycloneDX tool
    run: npm install -g @cyclonedx/cyclonedx-npm

  - name: Generate SBOM
    run: |
      mkdir -p audit-reports
      cyclonedx-npm --output-format json --output-file audit-reports/sbom.json

  - name: Check report
    run: ls -l audit-reports

  - name: Upload to DefectDojo
    run: |
      curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
        -H "Authorization: Token $DEFECTDOJO_API_KEY" \
        -F 'scan_type=CycloneDX' \
        -F 'minimum_severity=Low' \
        -F 'active=true' \
        -F 'verified=false' \
        -F "engagement=1" \
        -F 'file=@audit-reports/sbom.json'
    env:
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
