name: Dependency CVE Scan

on:
  push:
    branches: [ master ]

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Run npm audit
        run: |
          mkdir -p audit-reports
          npm audit --json > audit-reports/npm-audit.json

      - name: Check report
        run: ls -l audit-reports

      - name: Upload to DefectDojo
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -F 'scan_type=Npm Audit Scan' \
            -F 'minimum_severity=Low' \
            -F 'active=true' \
            -F 'verified=false' \
            -F "engagement=1" \
            -F 'file=@audit-reports/npm-audit.json'
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
