name: OWASP ZAP Scan + DefectDojo Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run vulnerable app
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - name: Wait for app
        run: sleep 20
      - name: Run ZAP Scan
        run: |
          docker run -t -v $(pwd):/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:3000 \
            -r zap_report.html
      - name: Upload to DefectDojo
        run: |
          curl -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_KEY" \
            -F 'scan_type=ZAP Scan' \
            -F 'minimum_severity=Low' \
            -F 'active=true' \
            -F 'verified=false' \
            -F 'engagement=1' \
            -F 'file=@zap_report.html'
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
